#pragma once

#include <string>
#include <vector>
#include <cstdint>

enum lfg_chat_template {
    LFG_CHAT_TEMPLATE_CHATML,
    LFG_CHAT_TEMPLATE_LFG_2,
    LFG_CHAT_TEMPLATE_LFG_2_SYS,
    LFG_CHAT_TEMPLATE_LFG_2_SYS_BOS,
    LFG_CHAT_TEMPLATE_LFG_2_SYS_STRIP,
    LFG_CHAT_TEMPLATE_MISTRAL_V1,
    LFG_CHAT_TEMPLATE_MISTRAL_V3,
    LFG_CHAT_TEMPLATE_MISTRAL_V3_TEKKEN,
    LFG_CHAT_TEMPLATE_MISTRAL_V7,
    LFG_CHAT_TEMPLATE_MISTRAL_V7_TEKKEN,
    LFG_CHAT_TEMPLATE_PHI_3,
    LFG_CHAT_TEMPLATE_PHI_4,
    LFG_CHAT_TEMPLATE_FALCON_3,
    LFG_CHAT_TEMPLATE_ZEPHYR,
    LFG_CHAT_TEMPLATE_MONARCH,
    LFG_CHAT_TEMPLATE_GEMMA,
    LFG_CHAT_TEMPLATE_ORION,
    LFG_CHAT_TEMPLATE_OPENCHAT,
    LFG_CHAT_TEMPLATE_VICUNA,
    LFG_CHAT_TEMPLATE_VICUNA_ORCA,
    LFG_CHAT_TEMPLATE_DEEPSEEK,
    LFG_CHAT_TEMPLATE_DEEPSEEK_2,
    LFG_CHAT_TEMPLATE_DEEPSEEK_3,
    LFG_CHAT_TEMPLATE_COMMAND_R,
    LFG_CHAT_TEMPLATE_LFG_3,
    LFG_CHAT_TEMPLATE_CHATGLM_3,
    LFG_CHAT_TEMPLATE_CHATGLM_4,
    LFG_CHAT_TEMPLATE_GLMEDGE,
    LFG_CHAT_TEMPLATE_MINICPM,
    LFG_CHAT_TEMPLATE_EXAONE_3,
    LFG_CHAT_TEMPLATE_EXAONE_4,
    LFG_CHAT_TEMPLATE_EXAONE_MOE,
    LFG_CHAT_TEMPLATE_RWKV_WORLD,
    LFG_CHAT_TEMPLATE_GRANITE,
    LFG_CHAT_TEMPLATE_GIGACHAT,
    LFG_CHAT_TEMPLATE_MEGREZ,
    LFG_CHAT_TEMPLATE_YANDEX,
    LFG_CHAT_TEMPLATE_BAILING,
    LFG_CHAT_TEMPLATE_BAILING_THINK,
    LFG_CHAT_TEMPLATE_BAILING2,
    LFG_CHAT_TEMPLATE_LIQUID4,
    LFG_CHAT_TEMPLATE_SMOLVLM,
    LFG_CHAT_TEMPLATE_DOTS1,
    LFG_CHAT_TEMPLATE_HUNYUAN_MOE,
    LFG_CHAT_TEMPLATE_OPENAI_MOE,
    LFG_CHAT_TEMPLATE_HUNYUAN_DENSE,
    LFG_CHAT_TEMPLATE_KIMI_K2,
    LFG_CHAT_TEMPLATE_SEED_OSS,
    LFG_CHAT_TEMPLATE_GROK_2,
    LFG_CHAT_TEMPLATE_PANGU_EMBED,
    LFG_CHAT_TEMPLATE_SOLAR_OPEN,
    LFG_CHAT_TEMPLATE_UNKNOWN,
};

struct lfg_chat_message;

lfg_chat_template lfg_chat_template_from_str(const std::string & name);

lfg_chat_template lfg_chat_detect_template(const std::string & tmpl);

int32_t lfg_chat_apply_template(
    lfg_chat_template tmpl,
    const std::vector<const lfg_chat_message *> & chat,
    std::string & dest, bool add_ass);
