#include "lfg_arch.h"

#include "lfg_impl.h"

#include <map>
#include <set>

static const std::map<lfg_arch_enum, const char *> LFG_ARCH_NAMES = {
    { LFG_ARCH_LFM2,             "lfm2"             },
    { LFG_ARCH_LFM2MOE,          "lfm2moe"          },
    { LFG_ARCH_BERT,             "bert"             },
    { LFG_ARCH_NOMIC_BERT,       "nomic-bert"       },
    { LFG_ARCH_NOMIC_BERT_MOE,   "nomic-bert-moe"   },
    { LFG_ARCH_JINA_BERT_V2,     "jina-bert-v2"     },
    { LFG_ARCH_JINA_BERT_V3,     "jina-bert-v3"     },
    { LFG_ARCH_NEO_BERT,         "neo-bert"         },
    { LFG_ARCH_MODERN_BERT,      "modern-bert"      },
    { LFG_ARCH_UNKNOWN,          "(unknown)"        },
};

static const std::map<lfg_kv_enum, const char *> LFG_KV_NAMES = {
    { LFG_KV_GENERAL_TYPE,                     "general.type"                          },
    { LFG_KV_GENERAL_ARCHITECTURE,             "general.architecture"                  },
    { LFG_KV_GENERAL_QUANTIZATION_VERSION,     "general.quantization_version"          },
    { LFG_KV_GENERAL_ALIGNMENT,                "general.alignment"                     },
    { LFG_KV_GENERAL_FILE_TYPE,                "general.file_type"                     },
    { LFG_KV_GENERAL_SAMPLING_SEQUENCE,        "general.sampling.sequence"             },
    { LFG_KV_GENERAL_SAMPLING_TOP_K,           "general.sampling.top_k"                },
    { LFG_KV_GENERAL_SAMPLING_TOP_P,           "general.sampling.top_p"                },
    { LFG_KV_GENERAL_SAMPLING_MIN_P,           "general.sampling.min_p"                },
    { LFG_KV_GENERAL_SAMPLING_XTC_PROBABILITY, "general.sampling.xtc_probability"      },
    { LFG_KV_GENERAL_SAMPLING_XTC_THRESHOLD,   "general.sampling.xtc_threshold"        },
    { LFG_KV_GENERAL_SAMPLING_TEMP,            "general.sampling.temp"                 },
    { LFG_KV_GENERAL_SAMPLING_PENALTY_LAST_N,  "general.sampling.penalty_last_n"       },
    { LFG_KV_GENERAL_SAMPLING_PENALTY_REPEAT,  "general.sampling.penalty_repeat"       },
    { LFG_KV_GENERAL_SAMPLING_MIROSTAT,        "general.sampling.mirostat"             },
    { LFG_KV_GENERAL_SAMPLING_MIROSTAT_TAU,    "general.sampling.mirostat_tau"         },
    { LFG_KV_GENERAL_SAMPLING_MIROSTAT_ETA,    "general.sampling.mirostat_eta"         },
    { LFG_KV_GENERAL_NAME,                     "general.name"                          },
    { LFG_KV_GENERAL_AUTHOR,                   "general.author"                        },
    { LFG_KV_GENERAL_VERSION,                  "general.version"                       },
    { LFG_KV_GENERAL_URL,                      "general.url"                           },
    { LFG_KV_GENERAL_DESCRIPTION,              "general.description"                   },
    { LFG_KV_GENERAL_LICENSE,                  "general.license"                       },
    { LFG_KV_GENERAL_SOURCE_URL,               "general.source.url"                    },
    { LFG_KV_GENERAL_SOURCE_HF_REPO,           "general.source.huggingface.repository" },

    { LFG_KV_VOCAB_SIZE,                        "%s.vocab_size"                        },
    { LFG_KV_CONTEXT_LENGTH,                    "%s.context_length"                    },
    { LFG_KV_EMBEDDING_LENGTH,                  "%s.embedding_length"                  },
    { LFG_KV_EMBEDDING_LENGTH_OUT,              "%s.embedding_length_out"              },
    { LFG_KV_FEATURES_LENGTH,                   "%s.features_length"                   },
    { LFG_KV_BLOCK_COUNT,                       "%s.block_count"                       },
    { LFG_KV_LEADING_DENSE_BLOCK_COUNT,         "%s.leading_dense_block_count"         },
    { LFG_KV_FEED_FORWARD_LENGTH,               "%s.feed_forward_length"               },
    { LFG_KV_EXPERT_FEED_FORWARD_LENGTH,        "%s.expert_feed_forward_length"        },
    { LFG_KV_EXPERT_SHARED_FEED_FORWARD_LENGTH, "%s.expert_shared_feed_forward_length" },
    { LFG_KV_EXPERT_CHUNK_FEED_FORWARD_LENGTH,  "%s.expert_chunk_feed_forward_length"  },
    { LFG_KV_USE_PARALLEL_RESIDUAL,             "%s.use_parallel_residual"             },
    { LFG_KV_TENSOR_DATA_LAYOUT,                "%s.tensor_data_layout"                },
    { LFG_KV_EXPERT_COUNT,                      "%s.expert_count"                      },
    { LFG_KV_EXPERT_USED_COUNT,                 "%s.expert_used_count"                 },
    { LFG_KV_EXPERT_SHARED_COUNT,               "%s.expert_shared_count"               },
    { LFG_KV_EXPERT_GROUP_COUNT,                "%s.expert_group_count"                },
    { LFG_KV_EXPERT_GROUP_USED_COUNT,           "%s.expert_group_used_count"           },
    { LFG_KV_EXPERT_WEIGHTS_SCALE,              "%s.expert_weights_scale"              },
    { LFG_KV_EXPERT_WEIGHTS_NORM,               "%s.expert_weights_norm"               },
    { LFG_KV_EXPERT_GATING_FUNC,                "%s.expert_gating_func"                },
    { LFG_KV_EXPERT_GROUP_SCALE,                "%s.expert_group_scale"                },
    { LFG_KV_EXPERTS_PER_GROUP,                 "%s.experts_per_group"                 },
    { LFG_KV_MOE_EVERY_N_LAYERS,                "%s.moe_every_n_layers"                },
    { LFG_KV_NEXTN_PREDICT_LAYERS,              "%s.nextn_predict_layers"              },
    { LFG_KV_NUM_DEEPSTACK_LAYERS,              "%s.n_deepstack_layers"                },
    { LFG_KV_POOLING_TYPE,                      "%s.pooling_type"                      },
    { LFG_KV_LOGIT_SCALE,                       "%s.logit_scale"                       },
    { LFG_KV_DECODER_START_TOKEN_ID,            "%s.decoder_start_token_id"            },
    { LFG_KV_DECODER_BLOCK_COUNT,               "%s.decoder_block_count"               },
    { LFG_KV_ATTN_LOGIT_SOFTCAPPING,            "%s.attn_logit_softcapping"            },
    { LFG_KV_ROUTER_LOGIT_SOFTCAPPING,          "%s.router_logit_softcapping"          },
    { LFG_KV_FINAL_LOGIT_SOFTCAPPING,           "%s.final_logit_softcapping"           },
    { LFG_KV_SWIN_NORM,                         "%s.swin_norm"                         },
    { LFG_KV_RESCALE_EVERY_N_LAYERS,            "%s.rescale_every_n_layers"            },
    { LFG_KV_TIME_MIX_EXTRA_DIM,                "%s.time_mix_extra_dim"                },
    { LFG_KV_TIME_DECAY_EXTRA_DIM,              "%s.time_decay_extra_dim"              },
    { LFG_KV_RESIDUAL_SCALE,                    "%s.residual_scale"                    },
    { LFG_KV_EMBEDDING_SCALE,                   "%s.embedding_scale"                   },
    { LFG_KV_TOKEN_SHIFT_COUNT,                 "%s.token_shift_count"                 },
    { LFG_KV_INTERLEAVE_MOE_LAYER_STEP,         "%s.interleave_moe_layer_step"         },

    { LFG_KV_ATTENTION_HEAD_COUNT,                   "%s.attention.head_count"                   },
    { LFG_KV_ATTENTION_HEAD_COUNT_KV,                "%s.attention.head_count_kv"                },
    { LFG_KV_ATTENTION_MAX_ALIBI_BIAS,               "%s.attention.max_alibi_bias"               },
    { LFG_KV_ATTENTION_CLAMP_KQV,                    "%s.attention.clamp_kqv"                    },
    { LFG_KV_ATTENTION_KEY_LENGTH,                   "%s.attention.key_length"                   },
    { LFG_KV_ATTENTION_VALUE_LENGTH,                 "%s.attention.value_length"                 },
    { LFG_KV_ATTENTION_LAYERNORM_EPS,                "%s.attention.layer_norm_epsilon"           },
    { LFG_KV_ATTENTION_LAYERNORM_RMS_EPS,            "%s.attention.layer_norm_rms_epsilon"       },
    { LFG_KV_ATTENTION_GROUPNORM_EPS,                "%s.attention.group_norm_epsilon"           },
    { LFG_KV_ATTENTION_GROUPNORM_GROUPS,             "%s.attention.group_norm_groups"            },
    { LFG_KV_ATTENTION_CAUSAL,                       "%s.attention.causal"                       },
    { LFG_KV_ATTENTION_Q_LORA_RANK,                  "%s.attention.q_lora_rank"                  },
    { LFG_KV_ATTENTION_KV_LORA_RANK,                 "%s.attention.kv_lora_rank"                 },
    { LFG_KV_ATTENTION_DECAY_LORA_RANK,              "%s.attention.decay_lora_rank"              },
    { LFG_KV_ATTENTION_ICLR_LORA_RANK,               "%s.attention.iclr_lora_rank"               },
    { LFG_KV_ATTENTION_VALUE_RESIDUAL_MIX_LORA_RANK, "%s.attention.value_residual_mix_lora_rank" },
    { LFG_KV_ATTENTION_GATE_LORA_RANK,               "%s.attention.gate_lora_rank"               },
    { LFG_KV_ATTENTION_RELATIVE_BUCKETS_COUNT,       "%s.attention.relative_buckets_count"       },
    { LFG_KV_ATTENTION_SLIDING_WINDOW,               "%s.attention.sliding_window"               },
    { LFG_KV_ATTENTION_SLIDING_WINDOW_PATTERN,       "%s.attention.sliding_window_pattern"       },
    { LFG_KV_ATTENTION_SCALE,                        "%s.attention.scale"                        },
    { LFG_KV_ATTENTION_OUTPUT_SCALE,                 "%s.attention.output_scale"                 },
    { LFG_KV_ATTENTION_TEMPERATURE_LENGTH,           "%s.attention.temperature_length"           },
    { LFG_KV_ATTENTION_TEMPERATURE_SCALE,            "%s.attention.temperature_scale"            },
    { LFG_KV_ATTENTION_KEY_LENGTH_MLA,               "%s.attention.key_length_mla"               },
    { LFG_KV_ATTENTION_VALUE_LENGTH_MLA,             "%s.attention.value_length_mla"             },

    { LFG_KV_ROPE_DIMENSION_COUNT,          "%s.rope.dimension_count"                 },
    { LFG_KV_ROPE_DIMENSION_SECTIONS,       "%s.rope.dimension_sections"              },
    { LFG_KV_ROPE_FREQ_BASE,                "%s.rope.freq_base"                       },
    { LFG_KV_ROPE_FREQ_BASE_SWA,            "%s.rope.freq_base_swa"                   },
    { LFG_KV_ROPE_SCALE_LINEAR,             "%s.rope.scale_linear"                    },
    { LFG_KV_ROPE_SCALING_TYPE,             "%s.rope.scaling.type"                    },
    { LFG_KV_ROPE_SCALING_FACTOR,           "%s.rope.scaling.factor"                  },
    { LFG_KV_ROPE_SCALING_ATTN_FACTOR,      "%s.rope.scaling.attn_factor"             },
    { LFG_KV_ROPE_SCALING_ORIG_CTX_LEN,     "%s.rope.scaling.original_context_length" },
    { LFG_KV_ROPE_SCALING_FINETUNED,        "%s.rope.scaling.finetuned"               },
    { LFG_KV_ROPE_SCALING_YARN_LOG_MUL,     "%s.rope.scaling.yarn_log_multiplier"     },
    { LFG_KV_ROPE_SCALING_YARN_EXT_FACTOR,  "%s.rope.scaling.yarn_ext_factor"         },
    { LFG_KV_ROPE_SCALING_YARN_ATTN_FACTOR, "%s.rope.scaling.yarn_attn_factor"        },
    { LFG_KV_ROPE_SCALING_YARN_BETA_FAST,   "%s.rope.scaling.yarn_beta_fast"          },
    { LFG_KV_ROPE_SCALING_YARN_BETA_SLOW,   "%s.rope.scaling.yarn_beta_slow"          },

    { LFG_KV_SPLIT_NO,            "split.no"            },
    { LFG_KV_SPLIT_COUNT,         "split.count"         },
    { LFG_KV_SPLIT_TENSORS_COUNT, "split.tensors.count" },

    { LFG_KV_SSM_CONV_KERNEL,    "%s.ssm.conv_kernel"    },
    { LFG_KV_SSM_INNER_SIZE,     "%s.ssm.inner_size"     },
    { LFG_KV_SSM_STATE_SIZE,     "%s.ssm.state_size"     },
    { LFG_KV_SSM_TIME_STEP_RANK, "%s.ssm.time_step_rank" },
    { LFG_KV_SSM_GROUP_COUNT,    "%s.ssm.group_count"    },
    { LFG_KV_SSM_DT_B_C_RMS,     "%s.ssm.dt_b_c_rms"     },

    { LFG_KV_WKV_HEAD_SIZE, "%s.wkv.head_size" },

    { LFG_KV_POSNET_EMBEDDING_LENGTH, "%s.posnet.embedding_length" },
    { LFG_KV_POSNET_BLOCK_COUNT,      "%s.posnet.block_count"      },

    { LFG_KV_CONVNEXT_EMBEDDING_LENGTH, "%s.convnext.embedding_length" },
    { LFG_KV_CONVNEXT_BLOCK_COUNT,      "%s.convnext.block_count"      },

    { LFG_KV_CLASSIFIER_OUTPUT_LABELS, "%s.classifier.output_labels" },

    { LFG_KV_SHORTCONV_L_CACHE, "%s.shortconv.l_cache" },
    // sentence-transformers dense modules feature dims
    { LFG_KV_DENSE_2_FEAT_IN,        "%s.dense_2_feat_in"  },
    { LFG_KV_DENSE_2_FEAT_OUT,       "%s.dense_2_feat_out"  },
    { LFG_KV_DENSE_3_FEAT_IN,        "%s.dense_3_feat_in"   },
    { LFG_KV_DENSE_3_FEAT_OUT,       "%s.dense_3_feat_out"  },

    { LFG_KV_TOKENIZER_MODEL,                "tokenizer.ggml.model"                    },
    { LFG_KV_TOKENIZER_PRE,                  "tokenizer.ggml.pre"                      },
    { LFG_KV_TOKENIZER_LIST,                 "tokenizer.ggml.tokens"                   },
    { LFG_KV_TOKENIZER_TOKEN_TYPE,           "tokenizer.ggml.token_type"               },
    { LFG_KV_TOKENIZER_TOKEN_TYPE_COUNT,     "tokenizer.ggml.token_type_count"         },
    { LFG_KV_TOKENIZER_SCORES,               "tokenizer.ggml.scores"                   },
    { LFG_KV_TOKENIZER_MERGES,               "tokenizer.ggml.merges"                   },
    { LFG_KV_TOKENIZER_BOS_ID,               "tokenizer.ggml.bos_token_id"             },
    { LFG_KV_TOKENIZER_EOS_ID,               "tokenizer.ggml.eos_token_id"             },
    { LFG_KV_TOKENIZER_EOT_ID,               "tokenizer.ggml.eot_token_id"             },
    { LFG_KV_TOKENIZER_EOM_ID,               "tokenizer.ggml.eom_token_id"             },
    { LFG_KV_TOKENIZER_UNK_ID,               "tokenizer.ggml.unknown_token_id"         },
    { LFG_KV_TOKENIZER_SEP_ID,               "tokenizer.ggml.seperator_token_id"       },
    { LFG_KV_TOKENIZER_PAD_ID,               "tokenizer.ggml.padding_token_id"         },
    { LFG_KV_TOKENIZER_CLS_ID,               "tokenizer.ggml.cls_token_id"             },
    { LFG_KV_TOKENIZER_MASK_ID,              "tokenizer.ggml.mask_token_id"            },
    { LFG_KV_TOKENIZER_ADD_BOS,              "tokenizer.ggml.add_bos_token"            },
    { LFG_KV_TOKENIZER_ADD_EOS,              "tokenizer.ggml.add_eos_token"            },
    { LFG_KV_TOKENIZER_ADD_SEP,              "tokenizer.ggml.add_sep_token"            },
    { LFG_KV_TOKENIZER_ADD_PREFIX,           "tokenizer.ggml.add_space_prefix"         },
    { LFG_KV_TOKENIZER_REMOVE_EXTRA_WS,      "tokenizer.ggml.remove_extra_whitespaces" },
    { LFG_KV_TOKENIZER_PRECOMPILED_CHARSMAP, "tokenizer.ggml.precompiled_charsmap"     },
    { LFG_KV_TOKENIZER_HF_JSON,              "tokenizer.huggingface.json"              },
    { LFG_KV_TOKENIZER_RWKV,                 "tokenizer.rwkv.world"                    },
    { LFG_KV_TOKENIZER_CHAT_TEMPLATE,        "tokenizer.chat_template"                 },
    { LFG_KV_TOKENIZER_FIM_PRE_ID,           "tokenizer.ggml.fim_pre_token_id"         },
    { LFG_KV_TOKENIZER_FIM_SUF_ID,           "tokenizer.ggml.fim_suf_token_id"         },
    { LFG_KV_TOKENIZER_FIM_MID_ID,           "tokenizer.ggml.fim_mid_token_id"         },
    { LFG_KV_TOKENIZER_FIM_PAD_ID,           "tokenizer.ggml.fim_pad_token_id"         },
    { LFG_KV_TOKENIZER_FIM_REP_ID,           "tokenizer.ggml.fim_rep_token_id"         },
    { LFG_KV_TOKENIZER_FIM_SEP_ID,           "tokenizer.ggml.fim_sep_token_id"         },

    { LFG_KV_ADAPTER_TYPE,                    "adapter.type"               },
    { LFG_KV_ADAPTER_LORA_ALPHA,              "adapter.lora.alpha"         },
    { LFG_KV_ADAPTER_LORA_TASK_NAME,          "adapter.lora.task_name"     },
    { LFG_KV_ADAPTER_LORA_PROMPT_PREFIX,      "adapter.lora.prompt_prefix" },
    { LFG_KV_ADAPTER_ALORA_INVOCATION_TOKENS, "adapter.alora.invocation_tokens" },

    { LFG_KV_XIELU_ALPHA_N,         "xielu.alpha_n"         },
    { LFG_KV_XIELU_ALPHA_P,         "xielu.alpha_p"         },
    { LFG_KV_XIELU_BETA,            "xielu.beta"            },
    { LFG_KV_XIELU_EPS,             "xielu.eps"             },

    // deprecated
    { LFG_KV_TOKENIZER_PREFIX_ID, "tokenizer.ggml.prefix_token_id" },
    { LFG_KV_TOKENIZER_SUFFIX_ID, "tokenizer.ggml.suffix_token_id" },
    { LFG_KV_TOKENIZER_MIDDLE_ID, "tokenizer.ggml.middle_token_id" },
};

static const std::map<lfg_tensor_enum, const char *> LFG_TENSOR_NAMES = {
    { LFG_TENSOR_TOKEN_EMBD,                             "token_embd" },
    { LFG_TENSOR_OUTPUT_NORM,                            "output_norm" },
    { LFG_TENSOR_OUTPUT_NORM_LFM2,                       "token_embd_norm" }, // fix for wrong tensor name
    { LFG_TENSOR_OUTPUT,                                 "output" },
    { LFG_TENSOR_ROPE_FREQS,                             "rope_freqs" },
    { LFG_TENSOR_ATTN_NORM,                              "blk.%d.attn_norm" },
    { LFG_TENSOR_ATTN_Q,                                 "blk.%d.attn_q" },
    { LFG_TENSOR_ATTN_K,                                 "blk.%d.attn_k" },
    { LFG_TENSOR_ATTN_V,                                 "blk.%d.attn_v" },
    { LFG_TENSOR_ATTN_OUT,                               "blk.%d.attn_output" },
    { LFG_TENSOR_ATTN_ROT_EMBD,                          "blk.%d.attn_rot_embd" },
    { LFG_TENSOR_FFN_GATE_INP,                           "blk.%d.ffn_gate_inp" },
    { LFG_TENSOR_FFN_NORM,                               "blk.%d.ffn_norm" },
    { LFG_TENSOR_FFN_GATE,                               "blk.%d.ffn_gate" },
    { LFG_TENSOR_FFN_DOWN,                               "blk.%d.ffn_down" },
    { LFG_TENSOR_FFN_UP,                                 "blk.%d.ffn_up" },
    { LFG_TENSOR_FFN_GATE_EXP,                           "blk.%d.ffn_gate.%d" },
    { LFG_TENSOR_FFN_DOWN_EXP,                           "blk.%d.ffn_down.%d" },
    { LFG_TENSOR_FFN_UP_EXP,                             "blk.%d.ffn_up.%d" },
    { LFG_TENSOR_FFN_GATE_EXPS,                          "blk.%d.ffn_gate_exps" },
    { LFG_TENSOR_FFN_DOWN_EXPS,                          "blk.%d.ffn_down_exps" },
    { LFG_TENSOR_FFN_UP_EXPS,                            "blk.%d.ffn_up_exps" },
    { LFG_TENSOR_ATTN_POST_NORM,                         "blk.%d.post_attention_norm" },
    { LFG_TENSOR_ATTN_Q_NORM,                            "blk.%d.attn_q_norm" },
    { LFG_TENSOR_ATTN_K_NORM,                            "blk.%d.attn_k_norm" },
    { LFG_TENSOR_ATTN_GATE,                              "blk.%d.attn_gate" },
    { LFG_TENSOR_FFN_POST_NORM,                          "blk.%d.post_ffw_norm" },
    { LFG_TENSOR_FFN_GATE_SHEXP,                         "blk.%d.ffn_gate_shexp" },
    { LFG_TENSOR_FFN_UP_SHEXP,                           "blk.%d.ffn_up_shexp" },
    { LFG_TENSOR_FFN_DOWN_SHEXP,                         "blk.%d.ffn_down_shexp" },
    { LFG_TENSOR_FFN_EXP_PROBS_B,                        "blk.%d.exp_probs_b" },
    { LFG_TENSOR_ATTN_NORM_2,                            "blk.%d.attn_norm_2" },
    { LFG_TENSOR_ATTN_QKV,                               "blk.%d.attn_qkv" },
    { LFG_TENSOR_LAYER_OUT_NORM,                         "blk.%d.layer_output_norm" },
    { LFG_TENSOR_ATTN_OUT_NORM,                          "blk.%d.attn_output_norm" },
    { LFG_TENSOR_POS_EMBD,                               "position_embd" },
    { LFG_TENSOR_FFN_ACT,                                "blk.%d.ffn.act" },
    { LFG_TENSOR_TOKEN_EMBD_NORM,                        "token_embd_norm" },
    { LFG_TENSOR_TOKEN_TYPES,                            "token_types" },
    { LFG_TENSOR_CLS,                                    "cls" },
    { LFG_TENSOR_CLS_OUT,                                "cls.output" },
    { LFG_TENSOR_ENC_OUTPUT_NORM,                        "enc.output_norm" },
    { LFG_TENSOR_FFN_GATE_INP_SHEXP,                     "blk.%d.ffn_gate_inp_shexp" },
    { LFG_TENSOR_SSM_A_NOSCAN,                           "blk.%d.ssm_a" },
    { LFG_TENSOR_SSM_CONV1D,                             "blk.%d.ssm_conv1d" },
    { LFG_TENSOR_SSM_DT,                                 "blk.%d.ssm_dt" },
    { LFG_TENSOR_SSM_BETA_ALPHA,                         "blk.%d.ssm_ba" },
    { LFG_TENSOR_SSM_IN,                                 "blk.%d.ssm_in" },
    { LFG_TENSOR_SSM_NORM,                               "blk.%d.ssm_norm" },
    { LFG_TENSOR_SSM_OUT,                                "blk.%d.ssm_out" },
    { LFG_TENSOR_ROPE_FACTORS_LONG,                      "rope_factors_long" },
    { LFG_TENSOR_ROPE_FACTORS_SHORT,                     "rope_factors_short" },
    { LFG_TENSOR_SSM_X,                                  "blk.%d.ssm_x" },
    { LFG_TENSOR_SSM_A,                                  "blk.%d.ssm_a" },
    { LFG_TENSOR_SSM_D,                                  "blk.%d.ssm_d" },
    { LFG_TENSOR_SSM_DT_NORM,                            "blk.%d.ssm_dt_norm" },
    { LFG_TENSOR_SSM_B_NORM,                             "blk.%d.ssm_b_norm" },
    { LFG_TENSOR_SSM_C_NORM,                             "blk.%d.ssm_c_norm" },
    { LFG_TENSOR_ATTN_Q_A_NORM,                          "blk.%d.attn_q_a_norm" },
    { LFG_TENSOR_ATTN_KV_A_NORM,                         "blk.%d.attn_kv_a_norm" },
    { LFG_TENSOR_ATTN_Q_A,                               "blk.%d.attn_q_a" },
    { LFG_TENSOR_ATTN_Q_B,                               "blk.%d.attn_q_b" },
    { LFG_TENSOR_ATTN_KV_A_MQA,                          "blk.%d.attn_kv_a_mqa" },
    { LFG_TENSOR_ATTN_KV_B,                              "blk.%d.attn_kv_b" },
    { LFG_TENSOR_PER_LAYER_TOKEN_EMBD,                   "per_layer_token_embd" },
    { LFG_TENSOR_PER_LAYER_MODEL_PROJ,                   "per_layer_model_proj" },
    { LFG_TENSOR_PER_LAYER_PROJ_NORM,                    "per_layer_proj_norm" },
    { LFG_TENSOR_ALTUP_UNEMBD_PROJ,                      "altup_unembd_proj" },
    { LFG_TENSOR_ALTUP_PROJ,                             "altup_proj" },
    { LFG_TENSOR_PER_LAYER_INP_GATE,                     "blk.%d.inp_gate" },
    { LFG_TENSOR_PER_LAYER_PROJ,                         "blk.%d.proj" },
    { LFG_TENSOR_PER_LAYER_POST_NORM,                    "blk.%d.post_norm" },
    { LFG_TENSOR_ALTUP_CORRECT_COEF,                     "blk.%d.altup_correct_coef" },
    { LFG_TENSOR_ALTUP_CORRECT_SCALE,                    "blk.%d.altup_correct_scale" },
    { LFG_TENSOR_ALTUP_PREDICT_COEF,                     "blk.%d.altup_predict_coef" },
    { LFG_TENSOR_ALTUP_ROUTER,                           "blk.%d.altup_router" },
    { LFG_TENSOR_ALTUP_ROUTER_NORM,                      "blk.%d.altup_router_norm" },
    { LFG_TENSOR_LAUREL_L,                               "blk.%d.laurel_l" },
    { LFG_TENSOR_LAUREL_R,                               "blk.%d.laurel_r" },
    { LFG_TENSOR_LAUREL_POST_NORM,                       "blk.%d.laurel_post_norm" },
    { LFG_TENSOR_DENSE_2_OUT,                            "dense_2" },
    { LFG_TENSOR_DENSE_3_OUT,                            "dense_3" },
    { LFG_TENSOR_FFN_NORM_EXPS,                          "blk.%d.ffn_norm_exps" },
    { LFG_TENSOR_ATTN_K_B,                               "blk.%d.attn_k_b" },
    { LFG_TENSOR_ATTN_V_B,                               "blk.%d.attn_v_b" },
    { LFG_TENSOR_NEXTN_EH_PROJ,                          "blk.%d.nextn.eh_proj" },
    { LFG_TENSOR_NEXTN_EMBED_TOKENS,                     "blk.%d.nextn.embed_tokens" },
    { LFG_TENSOR_NEXTN_ENORM,                            "blk.%d.nextn.enorm" },
    { LFG_TENSOR_NEXTN_HNORM,                            "blk.%d.nextn.hnorm" },
    { LFG_TENSOR_NEXTN_SHARED_HEAD_HEAD,                 "blk.%d.nextn.shared_head_head" },
    { LFG_TENSOR_NEXTN_SHARED_HEAD_NORM,                 "blk.%d.nextn.shared_head_norm" },
    { LFG_TENSOR_ATTN_SUB_NORM,                          "blk.%d.attn_sub_norm" },
    { LFG_TENSOR_FFN_SUB_NORM,                           "blk.%d.ffn_sub_norm" },
    { LFG_TENSOR_DEC_OUTPUT_NORM,                        "dec.output_norm" },
    { LFG_TENSOR_DEC_ATTN_NORM,                          "dec.blk.%d.attn_norm" },
    { LFG_TENSOR_DEC_ATTN_Q,                             "dec.blk.%d.attn_q" },
    { LFG_TENSOR_DEC_ATTN_K,                             "dec.blk.%d.attn_k" },
    { LFG_TENSOR_DEC_ATTN_V,                             "dec.blk.%d.attn_v" },
    { LFG_TENSOR_DEC_ATTN_OUT,                           "dec.blk.%d.attn_o" },
    { LFG_TENSOR_DEC_ATTN_REL_B,                         "dec.blk.%d.attn_rel_b" },
    { LFG_TENSOR_DEC_CROSS_ATTN_NORM,                    "dec.blk.%d.cross_attn_norm" },
    { LFG_TENSOR_DEC_CROSS_ATTN_Q,                       "dec.blk.%d.cross_attn_q" },
    { LFG_TENSOR_DEC_CROSS_ATTN_K,                       "dec.blk.%d.cross_attn_k" },
    { LFG_TENSOR_DEC_CROSS_ATTN_V,                       "dec.blk.%d.cross_attn_v" },
    { LFG_TENSOR_DEC_CROSS_ATTN_OUT,                     "dec.blk.%d.cross_attn_o" },
    { LFG_TENSOR_DEC_CROSS_ATTN_REL_B,                   "dec.blk.%d.cross_attn_rel_b" },
    { LFG_TENSOR_DEC_FFN_NORM,                           "dec.blk.%d.ffn_norm" },
    { LFG_TENSOR_DEC_FFN_GATE,                           "dec.blk.%d.ffn_gate" },
    { LFG_TENSOR_DEC_FFN_DOWN,                           "dec.blk.%d.ffn_down" },
    { LFG_TENSOR_DEC_FFN_UP,                             "dec.blk.%d.ffn_up" },
    { LFG_TENSOR_ENC_ATTN_NORM,                          "enc.blk.%d.attn_norm" },
    { LFG_TENSOR_ENC_ATTN_Q,                             "enc.blk.%d.attn_q" },
    { LFG_TENSOR_ENC_ATTN_K,                             "enc.blk.%d.attn_k" },
    { LFG_TENSOR_ENC_ATTN_V,                             "enc.blk.%d.attn_v" },
    { LFG_TENSOR_ENC_ATTN_OUT,                           "enc.blk.%d.attn_o" },
    { LFG_TENSOR_ENC_ATTN_REL_B,                         "enc.blk.%d.attn_rel_b" },
    { LFG_TENSOR_ENC_FFN_NORM,                           "enc.blk.%d.ffn_norm" },
    { LFG_TENSOR_ENC_FFN_GATE,                           "enc.blk.%d.ffn_gate" },
    { LFG_TENSOR_ENC_FFN_DOWN,                           "enc.blk.%d.ffn_down" },
    { LFG_TENSOR_ENC_FFN_UP,                             "enc.blk.%d.ffn_up" },
    { LFG_TENSOR_TIME_MIX_W1,                            "blk.%d.time_mix_w1" },
    { LFG_TENSOR_TIME_MIX_W2,                            "blk.%d.time_mix_w2" },
    { LFG_TENSOR_TIME_MIX_LERP_X,                        "blk.%d.time_mix_lerp_x" },
    { LFG_TENSOR_TIME_MIX_LERP_W,                        "blk.%d.time_mix_lerp_w" },
    { LFG_TENSOR_TIME_MIX_LERP_K,                        "blk.%d.time_mix_lerp_k" },
    { LFG_TENSOR_TIME_MIX_LERP_V,                        "blk.%d.time_mix_lerp_v" },
    { LFG_TENSOR_TIME_MIX_LERP_R,                        "blk.%d.time_mix_lerp_r" },
    { LFG_TENSOR_TIME_MIX_LERP_G,                        "blk.%d.time_mix_lerp_g" },
    { LFG_TENSOR_TIME_MIX_LERP_FUSED,                    "blk.%d.time_mix_lerp_fused" },
    { LFG_TENSOR_TIME_MIX_FIRST,                         "blk.%d.time_mix_first" },
    { LFG_TENSOR_TIME_MIX_DECAY,                         "blk.%d.time_mix_decay" },
    { LFG_TENSOR_TIME_MIX_DECAY_W1,                      "blk.%d.time_mix_decay_w1" },
    { LFG_TENSOR_TIME_MIX_DECAY_W2,                      "blk.%d.time_mix_decay_w2" },
    { LFG_TENSOR_TIME_MIX_KEY,                           "blk.%d.time_mix_key" },
    { LFG_TENSOR_TIME_MIX_VALUE,                         "blk.%d.time_mix_value" },
    { LFG_TENSOR_TIME_MIX_RECEPTANCE,                    "blk.%d.time_mix_receptance" },
    { LFG_TENSOR_TIME_MIX_GATE,                          "blk.%d.time_mix_gate" },
    { LFG_TENSOR_TIME_MIX_LN,                            "blk.%d.time_mix_ln" },
    { LFG_TENSOR_TIME_MIX_OUTPUT,                        "blk.%d.time_mix_output" },
    { LFG_TENSOR_CHANNEL_MIX_LERP_K,                     "blk.%d.channel_mix_lerp_k" },
    { LFG_TENSOR_CHANNEL_MIX_LERP_R,                     "blk.%d.channel_mix_lerp_r" },
    { LFG_TENSOR_CHANNEL_MIX_KEY,                        "blk.%d.channel_mix_key" },
    { LFG_TENSOR_CHANNEL_MIX_VALUE,                      "blk.%d.channel_mix_value" },
    { LFG_TENSOR_CHANNEL_MIX_RECEPTANCE,                 "blk.%d.channel_mix_receptance" },
    { LFG_TENSOR_TIME_MIX_W0,                            "blk.%d.time_mix_w0" },
    { LFG_TENSOR_TIME_MIX_A0,                            "blk.%d.time_mix_a0" },
    { LFG_TENSOR_TIME_MIX_A1,                            "blk.%d.time_mix_a1" },
    { LFG_TENSOR_TIME_MIX_A2,                            "blk.%d.time_mix_a2" },
    { LFG_TENSOR_TIME_MIX_V0,                            "blk.%d.time_mix_v0" },
    { LFG_TENSOR_TIME_MIX_V1,                            "blk.%d.time_mix_v1" },
    { LFG_TENSOR_TIME_MIX_V2,                            "blk.%d.time_mix_v2" },
    { LFG_TENSOR_TIME_MIX_G1,                            "blk.%d.time_mix_g1" },
    { LFG_TENSOR_TIME_MIX_G2,                            "blk.%d.time_mix_g2" },
    { LFG_TENSOR_TIME_MIX_K_K,                           "blk.%d.time_mix_k_k" },
    { LFG_TENSOR_TIME_MIX_K_A,                           "blk.%d.time_mix_k_a" },
    { LFG_TENSOR_TIME_MIX_R_K,                           "blk.%d.time_mix_r_k" },
    { LFG_TENSOR_CONV1D,                                 "conv1d" },
    { LFG_TENSOR_CONVNEXT_DW,                            "convnext.%d.dw" },
    { LFG_TENSOR_CONVNEXT_NORM,                          "convnext.%d.norm" },
    { LFG_TENSOR_CONVNEXT_PW1,                           "convnext.%d.pw1" },
    { LFG_TENSOR_CONVNEXT_PW2,                           "convnext.%d.pw2" },
    { LFG_TENSOR_CONVNEXT_GAMMA,                         "convnext.%d.gamma" },
    { LFG_TENSOR_POS_NET_CONV1,                          "posnet.%d.conv1" },
    { LFG_TENSOR_POS_NET_CONV2,                          "posnet.%d.conv2" },
    { LFG_TENSOR_POS_NET_NORM,                           "posnet.%d.norm" },
    { LFG_TENSOR_POS_NET_NORM1,                          "posnet.%d.norm1" },
    { LFG_TENSOR_POS_NET_NORM2,                          "posnet.%d.norm2" },
    { LFG_TENSOR_POS_NET_ATTN_NORM,                      "posnet.%d.attn_norm" },
    { LFG_TENSOR_POS_NET_ATTN_Q,                         "posnet.%d.attn_q" },
    { LFG_TENSOR_POS_NET_ATTN_K,                         "posnet.%d.attn_k" },
    { LFG_TENSOR_POS_NET_ATTN_V,                         "posnet.%d.attn_v" },
    { LFG_TENSOR_POS_NET_ATTN_OUT,                       "posnet.%d.attn_output" },
    { LFG_TENSOR_ATTN_SINKS,                             "blk.%d.attn_sinks" },
    { LFG_TENSOR_SHORTCONV_CONV,                         "blk.%d.shortconv.conv" },
    { LFG_TENSOR_SHORTCONV_INPROJ,                       "blk.%d.shortconv.in_proj" },
    { LFG_TENSOR_SHORTCONV_OUTPROJ,                      "blk.%d.shortconv.out_proj" },
    { LFG_TENSOR_FFN_GATE_CHEXPS,                        "blk.%d.ffn_gate_chexps" },
    { LFG_TENSOR_FFN_DOWN_CHEXPS,                        "blk.%d.ffn_down_chexps" },
    { LFG_TENSOR_FFN_UP_CHEXPS,                          "blk.%d.ffn_up_chexps" },
    { LFG_TENSOR_VISEXP_ATTN_QKV,                        "blk.%d.vis_attn_qkv" },
    { LFG_TENSOR_VISEXP_ATTN_OUT,                        "blk.%d.vis_attn_output" },
    { LFG_TENSOR_VISEXP_FFN_GATE,                        "blk.%d.vis_gate" },
    { LFG_TENSOR_VISEXP_FFN_DOWN,                        "blk.%d.vis_down" },
    { LFG_TENSOR_VISEXP_FFN_UP,                          "blk.%d.vis_up" },
};

static std::set<lfg_tensor_enum> lfg_get_tensor_names(lfg_arch_enum arch) {
    switch (arch) {
        case LFG_ARCH_LFM2:
            return {
                LFG_TENSOR_ATTN_NORM,
                LFG_TENSOR_ATTN_Q,
                LFG_TENSOR_ATTN_K,
                LFG_TENSOR_ATTN_V,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_ATTN_K_NORM,
                LFG_TENSOR_ATTN_Q_NORM,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_GATE,
                LFG_TENSOR_FFN_NORM,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_SHORTCONV_CONV,
                LFG_TENSOR_SHORTCONV_INPROJ,
                LFG_TENSOR_SHORTCONV_OUTPROJ,
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_OUTPUT_NORM_LFM2,
                LFG_TENSOR_OUTPUT,
                LFG_TENSOR_DENSE_2_OUT,
            };
        case LFG_ARCH_LFM2MOE:
            return {
                LFG_TENSOR_ATTN_NORM,
                LFG_TENSOR_ATTN_Q,
                LFG_TENSOR_ATTN_K,
                LFG_TENSOR_ATTN_V,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_ATTN_K_NORM,
                LFG_TENSOR_ATTN_Q_NORM,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_GATE,
                LFG_TENSOR_FFN_NORM,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_SHORTCONV_CONV,
                LFG_TENSOR_SHORTCONV_INPROJ,
                LFG_TENSOR_SHORTCONV_OUTPROJ,
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_OUTPUT_NORM_LFM2,
                LFG_TENSOR_FFN_GATE_INP,
                LFG_TENSOR_FFN_GATE_EXPS,
                LFG_TENSOR_FFN_DOWN_EXPS,
                LFG_TENSOR_FFN_UP_EXPS,
                LFG_TENSOR_FFN_EXP_PROBS_B,
            };
        case LFG_ARCH_BERT:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_TOKEN_EMBD_NORM,
                LFG_TENSOR_TOKEN_TYPES,
                LFG_TENSOR_POS_EMBD,
                LFG_TENSOR_ATTN_OUT_NORM,
                LFG_TENSOR_ATTN_QKV,
                LFG_TENSOR_ATTN_Q,
                LFG_TENSOR_ATTN_K,
                LFG_TENSOR_ATTN_V,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_LAYER_OUT_NORM,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_CLS,
                LFG_TENSOR_CLS_OUT,
            };
        case LFG_ARCH_NOMIC_BERT:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_TOKEN_EMBD_NORM,
                LFG_TENSOR_TOKEN_TYPES,
                LFG_TENSOR_ATTN_OUT_NORM,
                LFG_TENSOR_ATTN_QKV,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_LAYER_OUT_NORM,
                LFG_TENSOR_FFN_GATE,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_UP,
            };
        case LFG_ARCH_NOMIC_BERT_MOE:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_TOKEN_EMBD_NORM,
                LFG_TENSOR_TOKEN_TYPES,
                LFG_TENSOR_ATTN_OUT_NORM,
                LFG_TENSOR_ATTN_QKV,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_LAYER_OUT_NORM,
                LFG_TENSOR_FFN_GATE,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_FFN_GATE_INP,
                LFG_TENSOR_FFN_DOWN_EXPS,
                LFG_TENSOR_FFN_UP_EXPS,
            };
        case LFG_ARCH_JINA_BERT_V3:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_TOKEN_EMBD_NORM,
                LFG_TENSOR_TOKEN_TYPES,
                LFG_TENSOR_ATTN_OUT_NORM,
                LFG_TENSOR_ATTN_QKV,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_LAYER_OUT_NORM,
            };
        case LFG_ARCH_JINA_BERT_V2:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_TOKEN_EMBD_NORM,
                LFG_TENSOR_TOKEN_TYPES,
                LFG_TENSOR_ATTN_NORM_2,
                LFG_TENSOR_ATTN_OUT_NORM,
                LFG_TENSOR_ATTN_Q,
                LFG_TENSOR_ATTN_Q_NORM,
                LFG_TENSOR_ATTN_K,
                LFG_TENSOR_ATTN_K_NORM,
                LFG_TENSOR_ATTN_V,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_LAYER_OUT_NORM,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_GATE,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_CLS,
            };
        case LFG_ARCH_NEO_BERT:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_ATTN_NORM,
                LFG_TENSOR_ATTN_QKV,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_FFN_NORM,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_ENC_OUTPUT_NORM,
                LFG_TENSOR_CLS,
                LFG_TENSOR_CLS_OUT,
            };
        case LFG_ARCH_MODERN_BERT:
            return {
                LFG_TENSOR_TOKEN_EMBD,
                LFG_TENSOR_TOKEN_EMBD_NORM,
                LFG_TENSOR_OUTPUT_NORM,
                LFG_TENSOR_ATTN_NORM,
                LFG_TENSOR_ATTN_OUT,
                LFG_TENSOR_ATTN_QKV,
                LFG_TENSOR_FFN_DOWN,
                LFG_TENSOR_FFN_UP,
                LFG_TENSOR_FFN_NORM,
                LFG_TENSOR_CLS,
                LFG_TENSOR_CLS_OUT,
            };
        case LFG_ARCH_UNKNOWN:
            return {
                LFG_TENSOR_TOKEN_EMBD,
            };
        default:
            lfg_set_last_error(LFG_ERROR_UNSUPPORTED, "%s: unknown architecture for tensor mapping", __func__);
            return {};
    }
}

// declare information about the model weight tensors:
// - the layer in which the tensor is going to be used. this is needed in order to assign the correct buffer type for the weight
// - the operator which is going to use the weight. this is needed to determine if the respective backend supports the operator
//
// for example, input layers are usually assigned to CPU/host buffer types
//
// a mismatch between the declared information and the actual layer/op in which the tensor is used can lead to sub-optimal
//   assignment of the buffer types and extra overhead during computation
// example: https://github.com/ggml-org/liquid.cpp/pull/17548
//
static const std::map<lfg_tensor_enum, lfg_tensor_info> LFG_TENSOR_INFOS = {
    {LFG_TENSOR_TOKEN_EMBD,                 {LFG_TENSOR_LAYER_INPUT, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_POS_EMBD,                   {LFG_TENSOR_LAYER_INPUT, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_TOKEN_TYPES,                {LFG_TENSOR_LAYER_INPUT, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_TOKEN_EMBD_NORM,            {LFG_TENSOR_LAYER_INPUT, GGML_OP_MUL}},
    {LFG_TENSOR_OUTPUT,                     {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CLS,                        {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CLS_OUT,                    {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DENSE_2_OUT,                {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}}, // Dense layer output
    {LFG_TENSOR_DENSE_3_OUT,                {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}}, // Dense layer output
    {LFG_TENSOR_OUTPUT_NORM,                {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL}},
    {LFG_TENSOR_OUTPUT_NORM_LFM2,           {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL}},
    {LFG_TENSOR_DEC_OUTPUT_NORM,            {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL}},
    {LFG_TENSOR_ENC_OUTPUT_NORM,            {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL}},
    {LFG_TENSOR_ROPE_FREQS,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ROPE}},
    {LFG_TENSOR_ROPE_FACTORS_LONG,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ROPE}},
    {LFG_TENSOR_ROPE_FACTORS_SHORT,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ROPE}},
    {LFG_TENSOR_ATTN_Q,                     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_K,                     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_V,                     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_QKV,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_OUT,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_GATE,                  {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_GATE,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_DOWN,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_UP,                     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_DOWN_SHEXP,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_GATE_SHEXP,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_UP_SHEXP,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_Q_A,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_Q_B,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_KV_A_MQA,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_KV_B,                  {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_K_B,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_V_B,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ATTN_SINKS,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_SCALE}},
    {LFG_TENSOR_DEC_ATTN_Q,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_ATTN_K,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_ATTN_V,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_ATTN_OUT,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_CROSS_ATTN_Q,           {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_CROSS_ATTN_K,           {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_CROSS_ATTN_V,           {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_CROSS_ATTN_OUT,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_FFN_GATE,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_FFN_DOWN,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_DEC_FFN_UP,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_ATTN_Q,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_ATTN_K,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_ATTN_V,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_ATTN_OUT,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_FFN_GATE,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_FFN_DOWN,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ENC_FFN_UP,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_GATE_INP_SHEXP,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_GATE_INP,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_SSM_IN,                     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_SSM_X,                      {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_SSM_DT,                     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_SSM_OUT,                    {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_SSM_BETA_ALPHA,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_W1,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_W2,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_A1,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_A2,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_V1,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_V2,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_G1,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_G2,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_DECAY_W1,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_DECAY_W2,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_KEY,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_VALUE,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_RECEPTANCE,        {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_GATE,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_TIME_MIX_OUTPUT,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CHANNEL_MIX_KEY,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CHANNEL_MIX_RECEPTANCE,     {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CHANNEL_MIX_VALUE,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_FFN_ACT,                    {LFG_TENSOR_LAYER_REPEATING, GGML_OP_DIV}},
    {LFG_TENSOR_SSM_CONV1D,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_SSM_CONV}},
    {LFG_TENSOR_SSM_A,                      {LFG_TENSOR_LAYER_REPEATING, GGML_OP_SSM_SCAN}},
    {LFG_TENSOR_SSM_A_NOSCAN,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}}, // a version of SSM_A used for MUL instead of SSM_SCAN
    {LFG_TENSOR_SSM_DT_NORM,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_SSM_B_NORM,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_SSM_C_NORM,                 {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_SSM_D,                      {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_SSM_NORM,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_TIME_MIX_LERP_X,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_TIME_MIX_LN,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_CHANNEL_MIX_LERP_K,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_CHANNEL_MIX_LERP_R,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_TIME_MIX_K_K,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_TIME_MIX_K_A,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_TIME_MIX_R_K,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_TIME_MIX_LERP_W,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_LERP_K,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_LERP_V,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_LERP_R,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_LERP_G,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_LERP_FUSED,        {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_DECAY,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_W0,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_A0,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_V0,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    {LFG_TENSOR_TIME_MIX_FIRST,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_RWKV_WKV6}},
    {LFG_TENSOR_ATTN_NORM,                  {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_NORM_2,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_OUT_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_POST_NORM,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_FFN_NORM,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_FFN_POST_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_FFN_NORM_EXPS,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_Q_NORM,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_K_NORM,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_LAYER_OUT_NORM,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_Q_A_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_KV_A_NORM,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ATTN_SUB_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_FFN_SUB_NORM,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_DEC_ATTN_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_DEC_CROSS_ATTN_NORM,        {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_DEC_FFN_NORM,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ENC_ATTN_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ENC_FFN_NORM,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_DEC_ATTN_REL_B,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_ENC_ATTN_REL_B,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_FFN_DOWN_EXPS,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT_ID}},
    {LFG_TENSOR_FFN_GATE_EXPS,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT_ID}},
    {LFG_TENSOR_FFN_UP_EXPS,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT_ID}},
    {LFG_TENSOR_FFN_DOWN_CHEXPS,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT_ID}},
    {LFG_TENSOR_FFN_GATE_CHEXPS,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT_ID}},
    {LFG_TENSOR_FFN_UP_CHEXPS,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT_ID}},
    {LFG_TENSOR_FFN_EXP_PROBS_B,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_ADD}},
    // altup / laurel (gemma 3n)
    {LFG_TENSOR_PER_LAYER_TOKEN_EMBD,       {LFG_TENSOR_LAYER_OUTPUT,    GGML_OP_GET_ROWS}},
    {LFG_TENSOR_PER_LAYER_MODEL_PROJ,       {LFG_TENSOR_LAYER_OUTPUT,    GGML_OP_MUL_MAT}},
    {LFG_TENSOR_PER_LAYER_PROJ_NORM,        {LFG_TENSOR_LAYER_OUTPUT,    GGML_OP_MUL}},
    {LFG_TENSOR_ALTUP_PROJ,                 {LFG_TENSOR_LAYER_OUTPUT,    GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ALTUP_UNEMBD_PROJ,          {LFG_TENSOR_LAYER_OUTPUT,    GGML_OP_MUL_MAT}},
    {LFG_TENSOR_PER_LAYER_INP_GATE,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_PER_LAYER_PROJ,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_PER_LAYER_POST_NORM,        {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ALTUP_CORRECT_COEF,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ALTUP_CORRECT_SCALE,        {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_ALTUP_PREDICT_COEF,         {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ALTUP_ROUTER,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_ALTUP_ROUTER_NORM,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_LAUREL_L,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_LAUREL_R,                   {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_LAUREL_POST_NORM,           {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    // this tensor is loaded for T5, but never used
    {LFG_TENSOR_DEC_CROSS_ATTN_REL_B,       {LFG_TENSOR_LAYER_REPEATING, GGML_OP_NONE}},
    {LFG_TENSOR_CONV1D,                     {LFG_TENSOR_LAYER_INPUT,     GGML_OP_IM2COL}},
    {LFG_TENSOR_POS_NET_NORM,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_POS_NET_NORM1,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_POS_NET_NORM2,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_POS_NET_CONV1,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_IM2COL}},
    {LFG_TENSOR_POS_NET_CONV2,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_IM2COL}},
    {LFG_TENSOR_POS_NET_ATTN_NORM,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_POS_NET_ATTN_Q,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_POS_NET_ATTN_K,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_POS_NET_ATTN_V,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_POS_NET_ATTN_OUT,           {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CONVNEXT_DW,                {LFG_TENSOR_LAYER_REPEATING, GGML_OP_IM2COL}},
    {LFG_TENSOR_CONVNEXT_NORM,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_CONVNEXT_PW1,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CONVNEXT_PW2,               {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_CONVNEXT_GAMMA,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL}},
    {LFG_TENSOR_SHORTCONV_CONV,             {LFG_TENSOR_LAYER_REPEATING, GGML_OP_SSM_CONV}},
    {LFG_TENSOR_SHORTCONV_INPROJ,           {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_SHORTCONV_OUTPROJ,          {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_VISEXP_ATTN_QKV,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_VISEXP_ATTN_OUT,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_VISEXP_FFN_GATE,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_VISEXP_FFN_DOWN,            {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_VISEXP_FFN_UP,              {LFG_TENSOR_LAYER_REPEATING, GGML_OP_MUL_MAT}},
    // NextN/MTP tensors are currently ignored (reserved for future MTP support)
    // These tensors only exist in the last layer(s) and are treated as output tensors
    {LFG_TENSOR_NEXTN_EH_PROJ,              {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_NEXTN_EMBED_TOKENS,         {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_NEXTN_ENORM,                {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_GET_ROWS}},
    {LFG_TENSOR_NEXTN_HNORM,                {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL}},
    {LFG_TENSOR_NEXTN_SHARED_HEAD_HEAD,     {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL_MAT}},
    {LFG_TENSOR_NEXTN_SHARED_HEAD_NORM,     {LFG_TENSOR_LAYER_OUTPUT, GGML_OP_MUL}},
};

LFG_KV::LFG_KV(lfg_arch_enum arch, const char * suffix) : arch(arch), suffix(suffix) {}

std::string LFG_KV::operator()(lfg_kv_enum kv) const {
    std::string name = ::lfg_format(LFG_KV_NAMES.at(kv), LFG_ARCH_NAMES.at(arch));

    if (suffix != nullptr) {
        name += ".";
        name += suffix;
    }

    return name;
}

LFG_TN_IMPL::LFG_TN_IMPL(lfg_arch_enum arch, lfg_tensor_enum tensor, const char * suffix, int bid, int xid)
    : arch(arch), tensor(tensor), suffix(suffix), bid(bid), xid(xid),
      model_tensors(lfg_get_tensor_names(arch)) {}

std::string LFG_TN_IMPL::str() const {
    if (LFG_TENSOR_NAMES.find(tensor) == LFG_TENSOR_NAMES.end()) {
        lfg_set_last_error(LFG_ERROR_INVALID_ARGUMENT, "%s: unknown tensor id %d", __func__, static_cast<int>(tensor));
        return "";
    }

    if (model_tensors.find(tensor) == model_tensors.end()) {
        return LFG_TENSOR_NAMES.at(tensor);
    }

    std::string name = ::lfg_format(LFG_TENSOR_NAMES.at(tensor), bid, xid);
    if (suffix != nullptr) {
        name += ".";
        name += suffix;
    }

    return name;
}

const char * lfg_arch_name(lfg_arch_enum arch) {
    auto it = LFG_ARCH_NAMES.find(arch);
    if (it == LFG_ARCH_NAMES.end()) {
        return "unknown";
    }
    return it->second;
}

lfg_arch_enum lfg_arch_from_string(const std::string & name) {
    for (const auto & kv : LFG_ARCH_NAMES) { // NOLINT
        if (kv.second == name) {
            return kv.first;
        }
    }

    return LFG_ARCH_UNKNOWN;
}

const lfg_tensor_info & lfg_tensor_info_for(lfg_tensor_enum tensor) {
    return LFG_TENSOR_INFOS.at(tensor);
}

bool lfg_arch_is_recurrent(const lfg_arch_enum & /*arch*/) {
    return false;
}

bool lfg_arch_is_hybrid(const lfg_arch_enum & arch) {
    if (arch == LFG_ARCH_LFM2 || arch == LFG_ARCH_LFM2MOE) {
        return true;
    }
    return false;
}

bool lfg_arch_is_diffusion(const lfg_arch_enum & /*arch*/) {
    return false;
}
